dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: golang-http
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.3
- name: golang-http-2
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.1
- name: http3
  repository: http://bucketrepo/bucketrepo/charts/
  version: 0.0.2
